### ISSUE TITLE
Mold PM schedule is not working correctly. I cannot see the tables so I do not know what the issue is.

### ISSUE THREAD

**Issue by philolsonjr** [nishant-njs/mold_maintenance_db#117] opened 2015-05-07 18:10 UTC

**Comment by nishant-njs** [comment] 2015-05-08 11:20
Can you please elaborate what is not working correctly? Here are the screenshots from Access and Web -

Test 1)
![1a](https://cloud.githubusercontent.com/assets/7536874/7535392/2ea7afb0-f5a2-11e4-91e7-e07c97e7b099.jpg)

![1b](https://cloud.githubusercontent.com/assets/7536874/7535393/32e9c0ae-f5a2-11e4-827b-4606426461dc.jpg)

***********************************************************************************************************************
Test 2)
![2a](https://cloud.githubusercontent.com/assets/7536874/7535397/44cc44ea-f5a2-11e4-8082-9c12d01c84ea.jpg)

![2b](https://cloud.githubusercontent.com/assets/7536874/7535399/48c5ace4-f5a2-11e4-81f9-c25fc4e2fb45.jpg)

**Comment by philolsonjr** [comment] 2015-05-08 15:50
It does not create the next PM record due by the value on the pm interval.

**Comment by nishant-njs** [comment] 2015-05-11 09:56
Not sure what you are referring too. Please provide screenshots.

**Comment by philolsonjr** [comment] 2015-05-13 17:20
see email.

**Comment by nishant-njs** [comment] 2015-05-14 11:05
Inserting new row and updated related functionality. Please test and close the issue.

**Comment by philolsonjr** [comment] 2015-05-14 18:25
still not creating or show next pm after running 2000 parts.
![capture](https://cloud.githubusercontent.com/assets/11412673/7638671/1ee07c3a-fa3c-11e4-8253-486f0e456cf5.PNG)
![capture](https://cloud.githubusercontent.com/assets/11412673/7638694/34e99f8e-fa3c-11e4-9f74-7921824b2173.PNG)

Cannot see what is in the table. When creating a request there is no data for shot number.

**Comment by nishant-njs** [comment] 2015-05-15 08:36
You will have to guide us here. Not sure what the issue is. Not able to understand - "still not creating or show next pm after running 2000 parts."

May be the old data on server were obsolete - we've truncated the table. Can you try adding new records? If problem still persists, please record and email the video explaining the issues.
![1](https://cloud.githubusercontent.com/assets/7536874/7649123/938ff26a-fb07-11e4-9248-e2c5c88f6dd3.jpg)

**Comment by philolsonjr** [comment] 2015-05-15 17:18
![capture](https://cloud.githubusercontent.com/assets/11412673/7658048/6c5827e0-fafc-11e4-85bf-a576e3605524.PNG)
You have to read the code on each form and recreate it in you database

**Comment by nishant-njs** [comment] 2015-05-18 09:47
1) PM Database is Empty
![1](https://cloud.githubusercontent.com/assets/7536874/7678262/89db6568-fd70-11e4-946d-44cc995d37ff.jpg)

2) Create PM
![2](https://cloud.githubusercontent.com/assets/7536874/7678263/900577f8-fd70-11e4-9c4c-e69a5574109d.jpg)

3) Record in Database
![3](https://cloud.githubusercontent.com/assets/7536874/7678273/9b074d34-fd70-11e4-89d0-609dfdc907e9.jpg)

4) Updated PM record created in Step 2
![4](https://cloud.githubusercontent.com/assets/7536874/7678289/b00f3cdc-fd70-11e4-84af-55003ef119dd.jpg)

5) Record updated in database and a new record mold_pm_id = 115 is successfully inserted
![5](https://cloud.githubusercontent.com/assets/7536874/7678301/c5868d0e-fd70-11e4-8d32-07283db71c31.jpg)

Please test above steps. Also, please elaborate - "still not creating or show next pm after running 2000 parts."??

**Comment by philolsonjr** [comment] 2015-05-18 17:09
so if you have the new request create a setup and close it with 200 shots and see if the request for pm shows on your report.

**Comment by nishant-njs** [comment] 2015-05-20 12:52
Not able to locate this logic. Please share screenshots from MS Access along with code (if any).

**Comment by philolsonjr** [comment] 2015-05-20 18:14
I need to see the raw data table, if you cant recreate what is in the Access database.

When you complete a PM it creates a new pm record with the next due date, based on shot numbers.when the mold reaches that number it should be displayed on the PM report

**Comment by nishant-njs** [comment] 2015-05-21 12:08
Fixed. We've truncated "Mold PM Record Table". Please test and close the issue.

**Comment by nishant-njs** [comment] 2015-05-26 19:20
See last comment. We found the logic - it's fixed. Please test and close the issue.

**Comment by philolsonjr** [comment] 2015-05-27 15:38
![capture](https://cloud.githubusercontent.com/assets/11412673/7840239/0206bf46-045c-11e5-8192-1110cc5eb846.PNG)
Next PM number wrong.

**Comment by nishant-njs** [comment] 2015-05-28 12:27
PM number is calculating correctly. We tested again today. Below are the screenshots from UI and database...

1)
![1](https://cloud.githubusercontent.com/assets/7536874/7859668/b2a917cc-0560-11e5-9402-85dd3dc7a728.jpg)

2)
![2](https://cloud.githubusercontent.com/assets/7536874/7859670/b78a98ec-0560-11e5-91af-2af8a681b04c.jpg)

3)
![3](https://cloud.githubusercontent.com/assets/7536874/7859672/ba931884-0560-11e5-900e-573f9a2fb569.jpg)

4)
![4](https://cloud.githubusercontent.com/assets/7536874/7859675/bea4f622-0560-11e5-9611-4a4c1ea48b85.jpg)

5)
![5](https://cloud.githubusercontent.com/assets/7536874/7859680/c4114ff2-0560-11e5-94d6-560e4d7eba48.jpg)

6)
![6](https://cloud.githubusercontent.com/assets/7536874/7859683/c92d0fbc-0560-11e5-8290-4a40340df22c.jpg)

7)
![7](https://cloud.githubusercontent.com/assets/7536874/7859685/cd53f5c4-0560-11e5-99fb-e02ac21fa3da.jpg)

8)
![8](https://cloud.githubusercontent.com/assets/7536874/7859688/d23b0654-0560-11e5-8550-b0f90f72bd15.jpg)

9)
![9](https://cloud.githubusercontent.com/assets/7536874/7859689/d58e4226-0560-11e5-9c5f-baebb88f884f.jpg)

10)
![10](https://cloud.githubusercontent.com/assets/7536874/7859692/dac7b11e-0560-11e5-8263-5a187236cd8a.jpg)

11)
![11](https://cloud.githubusercontent.com/assets/7536874/7859695/df430572-0560-11e5-8b8a-101d901960ec.jpg)

12) 22600 (mold end number) - 21514 (mold start number) = 1086 + 22389 (previous Mold PM Wash Number) = 23475 (Mold PM Wash Number)
![12](https://cloud.githubusercontent.com/assets/7536874/7859945/91ca0e38-0562-11e5-9d0c-35276d9ad96f.jpg)

**Closed** 2015-06-01 17:49 UTC
